// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  blog: defineAsyncComponent(() => import("./Blog/index.vue")),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  features: defineAsyncComponent(() => import("./Features/index.vue")),
  form: defineAsyncComponent(() => import("./Form/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  media: defineAsyncComponent(() => import("./Media/index.vue")),
  project_grid: defineAsyncComponent(() => import("./ProjectGrid/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
});
